<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pisteCiclabiliMilano [
<!ELEMENT pisteCiclabiliMilano (pista*)>
<!ELEMENT pista (id, nomeVia, tipologia, sede)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nomeVia (#PCDATA)>
<!ELEMENT tipologia (#PCDATA)>
<!ELEMENT sede (nome, classe)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT classe (#PCDATA)>
<!ATTLIST classe nome CDATA #REQUIRED>
]>

<pisteCiclabiliMilano>
    <pista>
        <id>4</id>
        <nomeVia>PIAZZA GIOVANNI AMENDOLA</nomeVia>
        <tipologia>Pista ciclabile</tipologia>
        <sede>
            <nome>Sede propria</nome>
            <classe nome = "nicola"></classe>
        </sede>
    </pista>
    <pista>
        <id>6</id>
        <nomeVia>VIA CARLO AMORETTI</nomeVia>
        <tipologia>Pista ciclabile</tipologia>
        <sede>
            <nome>Sede propria</nome>
            <classe nome = "nicola"></classe>
        </sede>
    </pista>
    <pista>
        <id>16</id>
        <nomeVia>VIA ROBERTO ARDIGO'</nomeVia>
        <tipologia>No ordinanza</tipologia>
        <sede>
            <nome>Corsia ciclabile ricavata dal marciapiede</nome>
            <classe nome = "nicola"></classe>
        </sede>
    </pista>
    <pista>
        <id>30</id>
        <nomeVia>VIA CRISTINA BELGIOIOSO</nomeVia>
        <tipologia>No ordinanza</tipologia>
        <sede>
            <nome>Percorso promiscuo pedonale e ciclabile</nome>
            <classe nome = "nicola"></classe>
        </sede>
    </pista>
</pisteCiclabiliMilano>